spring.application.name=backend

# Configuración de la Base de Datos (Modifica según tus credenciales)
spring.datasource.url=jdbc:mysql://localhost:3306/basededatos?createDatabaseIfNotExist=true
spring.datasource.username=usuario
spring.datasource.password=contraseña
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Generación automática de tablas
spring.jpa.hibernate.ddl-auto=update

# Propiedades adicionales de JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true